apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue-deploy
  labels:
    app: blue-iteration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blue-iteration
  template:
    metadata:
      labels:
        app: blue-iteration
    spec:
      containers:
        - name: capstone
          image: xia0m/hello-site:latest
          ports:
            - containerPort: 80
